version: '3'
services:
  db:
    image: mysql:8.0
    container_name: "sample-app-db"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: go-sample-app
      MYSQL_USER: go
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    restart: always

  api:
    build: .
    container_name: "sample-app-api"
    volumes:
      - ./api:/app
    command: go run cmd/main.go
    ports:
      - "1323:1323"
    stdin_open: true
    tty: true

